/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-12 13:18:21.829308 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package gsm_s_1;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class GSM_S_1_ROLE_I1 extends AnB_Protocol<GSM_S_1_Steps,GSM_S_1_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	
	// local vars
	private AnBx_Params VAR_I1_R0 = null;
	private Crypto_ByteArray VAR_I1_J13I1R0 = null;
	private Crypto_ByteArray VAR_I1_J23I1R0 = null;
	private SecretKey VAR_I1_J33I1R0 = null;
	private Crypto_ByteArray VAR_I1_R2 = null;
	private Crypto_ByteArray VAR_I1_R4 = null;
	private SealedObject VAR_I1_R6 = null;
	private Crypto_ByteArray VAR_I1_DSI1R6I1J33I1R0 = null;
	
	
	public GSM_S_1_ROLE_I1(GSM_S_1_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		GSM_S_1_ROLE_I1.sessions = sessions;
		
		AnB_Session ROLE_I1_channel_ROLE_H_Server_Insecure = lbs.get("ROLE_I1_channel_ROLE_H_Server_Insecure");
        AnB_Session ROLE_I1_channel_ROLE_B_Client_Insecure = lbs.get("ROLE_I1_channel_ROLE_B_Client_Insecure");
        AnB_Session ROLE_I1_channel_ROLE_M_Client_Insecure = lbs.get("ROLE_I1_channel_ROLE_M_Client_Insecure");
        
		init();
		
        try {
            ROLE_I1_channel_ROLE_H_Server_Insecure.Open();
            ROLE_I1_channel_ROLE_B_Client_Insecure.Open();
            ROLE_I1_channel_ROLE_M_Client_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_I1_channel_ROLE_H_Server_Insecure, GSM_S_1_Steps.STEP_0);
                executeStep(ROLE_I1_channel_ROLE_B_Client_Insecure, GSM_S_1_Steps.STEP_1);
                executeStep(ROLE_I1_channel_ROLE_B_Client_Insecure, GSM_S_1_Steps.STEP_2);
                executeStep(ROLE_I1_channel_ROLE_M_Client_Insecure, GSM_S_1_Steps.STEP_3);
                executeStep(ROLE_I1_channel_ROLE_M_Client_Insecure, GSM_S_1_Steps.STEP_4);
                executeStep(ROLE_I1_channel_ROLE_B_Client_Insecure, GSM_S_1_Steps.STEP_5);
                executeStep(ROLE_I1_channel_ROLE_B_Client_Insecure, GSM_S_1_Steps.STEP_6);
                executeStep(ROLE_I1_channel_ROLE_M_Client_Insecure, GSM_S_1_Steps.STEP_7);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_I1_channel_ROLE_H_Server_Insecure.Close();
		    ROLE_I1_channel_ROLE_B_Client_Insecure.Close();
		    ROLE_I1_channel_ROLE_M_Client_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, GSM_S_1_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_0:
                
				noteqCheck("0.2",aliases.get("ROLE_I1"),aliases.get("ROLE_H"));
				noteqCheck("0.4",aliases.get("ROLE_I1"),aliases.get("ROLE_M"));
				noteqCheck("0.6",aliases.get("ROLE_I1"),aliases.get("ROLE_B"));
				VAR_I1_R0 = (AnBx_Params) s.Receive();
				VAR_I1_J13I1R0 = (Crypto_ByteArray) VAR_I1_R0.getValue(0);
				wffCheck("0.1",VAR_I1_J13I1R0);

                break;
                
            case STEP_1:
                
				VAR_I1_J23I1R0 = (Crypto_ByteArray) VAR_I1_R0.getValue(1);
				VAR_I1_J33I1R0 = (SecretKey) VAR_I1_R0.getValue(2);
				s.Send(new AnBx_Params(VAR_I1_J13I1R0,VAR_I1_J23I1R0,VAR_I1_J33I1R0));

                break;
                
            case STEP_2:
                
				VAR_I1_R2 = (Crypto_ByteArray) s.Receive();
				eqCheck("2.1",VAR_I1_R2,VAR_I1_J13I1R0);

                break;
                
            case STEP_3:
                
				s.Send(VAR_I1_R2);

                break;
                
            case STEP_4:
                
				VAR_I1_R4 = (Crypto_ByteArray) s.Receive();
				wffCheck("4.1",VAR_I1_R2);
				eqCheck("4.2",VAR_I1_R4,VAR_I1_J23I1R0);

                break;
                
            case STEP_5:
                
				s.Send(VAR_I1_R4);

                break;
                
            case STEP_6:
                
				VAR_I1_R6 = (SealedObject) s.Receive();
				wffCheck("6.1",VAR_I1_R4);
				VAR_I1_DSI1R6I1J33I1R0 = (Crypto_ByteArray) s.decrypt(VAR_I1_R6,VAR_I1_J33I1R0);
				wffCheck("6.2",VAR_I1_DSI1R6I1J33I1R0);

                break;
                
            case STEP_7:
                
				s.Send(s.encrypt(VAR_I1_DSI1R6I1J33I1R0,VAR_I1_J33I1R0));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	private SecretKey kc(AnB_Session s,Crypto_ByteArray par1,Crypto_ByteArray par2) {
		return GSM_S_1_Functions.kc(s,par1,par2);
	}
	
	

	
	

}