/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-12 13:18:21.829308 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package gsm_s_1;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class GSM_S_1_ROLE_M extends AnB_Protocol<GSM_S_1_Steps,GSM_S_1_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	
	// local vars
	private Crypto_ByteArray KiMH = null;
	private Crypto_ByteArray VAR_M_R3 = null;
	private Crypto_ByteArray VAR_M_KIMH = null;
	private SealedObject VAR_M_R7 = null;
	
	
	public GSM_S_1_ROLE_M(GSM_S_1_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         KiMH = (Crypto_ByteArray) AnB_Session.readObject(sharepath+"ki_"+aliases.get("ROLE_M")+"_"+aliases.get("ROLE_H")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		GSM_S_1_ROLE_M.sessions = sessions;
		
		AnB_Session ROLE_M_channel_ROLE_I1_Server_Insecure = lbs.get("ROLE_M_channel_ROLE_I1_Server_Insecure");
        
		init();
		
        try {
            ROLE_M_channel_ROLE_I1_Server_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_M_channel_ROLE_I1_Server_Insecure, GSM_S_1_Steps.STEP_3);
                executeStep(ROLE_M_channel_ROLE_I1_Server_Insecure, GSM_S_1_Steps.STEP_4);
                executeStep(ROLE_M_channel_ROLE_I1_Server_Insecure, GSM_S_1_Steps.STEP_7);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_M_channel_ROLE_I1_Server_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, GSM_S_1_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_3:
                
				VAR_M_R3 = (Crypto_ByteArray) s.Receive();
				wffCheck("3.1",VAR_M_R3);

                break;
                
            case STEP_4:
                
				VAR_M_KIMH = KiMH;
				s.Send(s.makeDigest(new AnBx_Params(VAR_M_R3,VAR_M_KIMH)));

                break;
                
            case STEP_7:
                
				VAR_M_R7 = (SealedObject) s.Receive();
				wffCheck("7.1",(Crypto_ByteArray) s.decrypt(VAR_M_R7,kc(s,VAR_M_R3,VAR_M_KIMH)));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	private SecretKey kc(AnB_Session s,Crypto_ByteArray par1,Crypto_ByteArray par2) {
		return GSM_S_1_Functions.kc(s,par1,par2);
	}
	
	

	
	

}