/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 13:06:46.709726 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package sso;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class SSO_ROLE_SP extends AnB_Protocol<SSO_Steps,SSO_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray ID = null;
	private Crypto_ByteArray Data = null;
	private AnBx_Params VAR_SP_R0 = null;
	private String VAR_SP_J13SPR0 = null;
	private Crypto_ByteArray VAR_SP_J33SPR0 = null;
	private AnBx_Params VAR_SP_R4 = null;
	private AnBx_Params VAR_SP_DJ12SPR4SIDP = null;
	
	
	public SSO_ROLE_SP(SSO_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		SSO_ROLE_SP.sessions = sessions;
		
		AnB_Session ROLE_SP_channel_ROLE_C_Server_Secure = lbs.get("ROLE_SP_channel_ROLE_C_Server_Secure");
        
		init();
		
        try {
            ROLE_SP_channel_ROLE_C_Server_Secure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_SP_channel_ROLE_C_Server_Secure, SSO_Steps.STEP_0);
                executeStep(ROLE_SP_channel_ROLE_C_Server_Secure, SSO_Steps.STEP_1);
                executeStep(ROLE_SP_channel_ROLE_C_Server_Secure, SSO_Steps.STEP_4);
                executeStep(ROLE_SP_channel_ROLE_C_Server_Secure, SSO_Steps.STEP_5);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_SP_channel_ROLE_C_Server_Secure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, SSO_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_0:
                
				VAR_SP_R0 = (AnBx_Params) s.Receive();
				eqCheck("0.1",aliases.get("ROLE_SP"),(String) VAR_SP_R0.getValue(1));
				//SB: added the following to have URI in the log
				wffCheck("0.2",(Crypto_ByteArray) VAR_SP_R0.getValue(2));

                break;
                
            case STEP_1:
                
				ID = s.getNonce();
				VAR_SP_J13SPR0 = (String) VAR_SP_R0.getValue(0);
				VAR_SP_J33SPR0 = (Crypto_ByteArray) VAR_SP_R0.getValue(2);
				s.Send(new AnBx_Params(VAR_SP_J13SPR0,aliases.get("ROLE_idp"),aliases.get("ROLE_SP"),ID,VAR_SP_J33SPR0));

                break;
                
            case STEP_4:
                
				VAR_SP_R4 = (AnBx_Params) s.Receive();
				VAR_SP_DJ12SPR4SIDP = (AnBx_Params) s.verify((SignedObject) VAR_SP_R4.getValue(0),aliases.get("ROLE_idp"));
				eqCheck("4.1",aliases.get("ROLE_idp"),(String) VAR_SP_DJ12SPR4SIDP.getValue(1));
				eqCheck("4.2",VAR_SP_J13SPR0,(String) VAR_SP_DJ12SPR4SIDP.getValue(0));
				eqCheck("4.3",VAR_SP_J33SPR0,(Crypto_ByteArray) VAR_SP_R4.getValue(1));

                break;
                
            case STEP_5:
                
				Data = s.getNonce();
				s.Send(Data);

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}