/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 11:20:15.065959 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package kerberos;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class Kerberos_ROLE_gw extends AnB_Protocol<Kerberos_Steps,Kerberos_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	private static Crypto_ByteArray tag = new Crypto_ByteArray("tag".getBytes());
	
	// local vars
	private SecretKey ShkAthgw = null;
	private SecretKey ShkGws = null;
	private Crypto_ByteArray T2 = null;
	private SecretKey KCS = null;
	private AnBx_Params VAR_GW_R2 = null;
	private AnBx_Params VAR_GW_DSJ34GWR2SHKATHGW = null;
	private AnBx_Params VAR_GW_DSJ44GWR2J45GWDSJ34GWR2SHKATHGW = null;
	private String VAR_GW_J25GWDSJ34GWR2SHKATHGW = null;
	
	
	public Kerberos_ROLE_gw(Kerberos_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkAthgw = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_ath")+"_"+aliases.get("ROLE_gw")+".ser");
		 ShkGws = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_gw")+"_"+aliases.get("ROLE_s")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		Kerberos_ROLE_gw.sessions = sessions;
		
		AnB_Session ROLE_gw_channel_ROLE_C_Server_Insecure = lbs.get("ROLE_gw_channel_ROLE_C_Server_Insecure");
        
		init();
		
        try {
            ROLE_gw_channel_ROLE_C_Server_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_gw_channel_ROLE_C_Server_Insecure, Kerberos_Steps.STEP_2);
                executeStep(ROLE_gw_channel_ROLE_C_Server_Insecure, Kerberos_Steps.STEP_3);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_gw_channel_ROLE_C_Server_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, Kerberos_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_2:
                
				VAR_GW_R2 = (AnBx_Params) s.Receive();
				VAR_GW_DSJ34GWR2SHKATHGW = (AnBx_Params) s.decrypt((SealedObject) VAR_GW_R2.getValue(2),ShkAthgw);
				eqCheck("2.1",aliases.get("ROLE_ath"),(String) VAR_GW_DSJ34GWR2SHKATHGW.getValue(0));
				eqCheck("2.2",aliases.get("ROLE_gw"),(String) VAR_GW_DSJ34GWR2SHKATHGW.getValue(2));
				eqCheck("2.3",aliases.get("ROLE_s"),(String) VAR_GW_R2.getValue(0));
				VAR_GW_DSJ44GWR2J45GWDSJ34GWR2SHKATHGW = (AnBx_Params) s.decrypt((SealedObject) VAR_GW_R2.getValue(3),(SecretKey) VAR_GW_DSJ34GWR2SHKATHGW.getValue(3));
				VAR_GW_J25GWDSJ34GWR2SHKATHGW = (String) VAR_GW_DSJ34GWR2SHKATHGW.getValue(1);
				eqCheck("2.4",VAR_GW_J25GWDSJ34GWR2SHKATHGW,(String) VAR_GW_DSJ44GWR2J45GWDSJ34GWR2SHKATHGW.getValue(0));
				eqCheck("2.5",(Crypto_ByteArray) VAR_GW_DSJ34GWR2SHKATHGW.getValue(4),(Crypto_ByteArray) VAR_GW_DSJ44GWR2J45GWDSJ34GWR2SHKATHGW.getValue(1));

                break;
                
            case STEP_3:
                
				T2 = s.getNonce();
				KCS = s.getSymmetricKey();
				s.Send(new AnBx_Params(VAR_GW_J25GWDSJ34GWR2SHKATHGW,s.encrypt(new AnBx_Params(VAR_GW_J25GWDSJ34GWR2SHKATHGW,aliases.get("ROLE_s"),KCS,T2),ShkGws),s.encrypt(new AnBx_Params(aliases.get("ROLE_s"),KCS,T2,(Crypto_ByteArray) VAR_GW_R2.getValue(1)),(SecretKey) VAR_GW_DSJ34GWR2SHKATHGW.getValue(3))));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}