/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-12 14:24:34.7413 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isopk2pmap;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class ISOPK2PMAP_ROLE_B extends AnB_Protocol<ISOPK2PMAP_Steps,ISOPK2PMAP_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	private static Crypto_ByteArray tag = new Crypto_ByteArray("tag".getBytes());
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray NxNB = null;
	private Crypto_ByteArray Text3 = null;
	private SignedObject VAR_B_R2 = null;
	private AnBx_Params VAR_B_R4 = null;
	private AnBx_Params VAR_B_DJ12BR4SS = null;
	
	
	public ISOPK2PMAP_ROLE_B(ISOPK2PMAP_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		ISOPK2PMAP_ROLE_B.sessions = sessions;
		
		AnB_Session ROLE_B_channel_ROLE_s_Server_Insecure = lbs.get("ROLE_B_channel_ROLE_s_Server_Insecure");
        AnB_Session ROLE_B_channel_ROLE_A_Client_Insecure = lbs.get("ROLE_B_channel_ROLE_A_Client_Insecure");
        
		init();
		
        try {
            ROLE_B_channel_ROLE_s_Server_Insecure.Open();
            ROLE_B_channel_ROLE_A_Client_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_B_channel_ROLE_s_Server_Insecure, ISOPK2PMAP_Steps.STEP_2);
                executeStep(ROLE_B_channel_ROLE_A_Client_Insecure, ISOPK2PMAP_Steps.STEP_3);
                executeStep(ROLE_B_channel_ROLE_A_Client_Insecure, ISOPK2PMAP_Steps.STEP_4);
                executeStep(ROLE_B_channel_ROLE_A_Client_Insecure, ISOPK2PMAP_Steps.STEP_5);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_B_channel_ROLE_s_Server_Insecure.Close();
		    ROLE_B_channel_ROLE_A_Client_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, ISOPK2PMAP_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_2:
                
				VAR_B_R2 = (SignedObject) s.Receive();
				eqCheck("2.1",(AnBx_Params) s.verify(VAR_B_R2,aliases.get("ROLE_s")),new AnBx_Params(aliases.get("ROLE_B"),s.getPublicKey(aliases.get("ROLE_B"),Crypto_KeyStoreType.sk())));

                break;
                
            case STEP_3:
                
				s.Send(empty);

                break;
                
            case STEP_4:
                
				VAR_B_R4 = (AnBx_Params) s.Receive();
				VAR_B_DJ12BR4SS = (AnBx_Params) s.verify((SignedObject) VAR_B_R4.getValue(0),aliases.get("ROLE_s"));
				eqCheck("4.1",aliases.get("ROLE_A"),(String) VAR_B_DJ12BR4SS.getValue(0));
				eqCheck("4.2",aliases.get("ROLE_B"),(String) new AnBx_Params((AnBx_Params) s.verify((SignedObject) VAR_B_R4.getValue(1),(PublicKey) VAR_B_DJ12BR4SS.getValue(1))).getValue(1));
				//SB: added to log the recovery of Text1
				wffCheck("4.3",(Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.verify((SignedObject) VAR_B_R4.getValue(1),(PublicKey) VAR_B_DJ12BR4SS.getValue(1))).getValue(2));

                break;
                
            case STEP_5:
                
                //SB: Cambiado orden de generación nonce: primero el que interesa
				Text3 = s.getNonce();
				NxNB = s.getNonce();

				s.Send(new AnBx_Params(VAR_B_R2,s.sign(new AnBx_Params(NxNB,aliases.get("ROLE_A"),Text3))));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}