/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 16:03:12.129783 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package sso_a2;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class SSO_A2_ROLE_C extends AnB_Protocol<SSO_A2_Steps,SSO_A2_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray URI = null;
	private Crypto_SealedPair VAR_C_R3 = null;
	private AnBx_Params VAR_C_DDCR3INVPCSSP = null;
	private Crypto_SealedPair VAR_C_R7 = null;
	private AnBx_Params VAR_C_DDCR7INVPCSIDP = null;
	private SignedObject VAR_C_J12CDDCR7INVPCSIDP = null;
	private Crypto_SealedPair VAR_C_R11 = null;
	
	
	public SSO_A2_ROLE_C(SSO_A2_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		SSO_A2_ROLE_C.sessions = sessions;
		
		AnB_Session ROLE_C_channel_ROLE_I_Client_Insecure = lbs.get("ROLE_C_channel_ROLE_I_Client_Insecure");
        
		init();
		
        try {
            ROLE_C_channel_ROLE_I_Client_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, SSO_A2_Steps.STEP_0);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, SSO_A2_Steps.STEP_3);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, SSO_A2_Steps.STEP_4);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, SSO_A2_Steps.STEP_7);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, SSO_A2_Steps.STEP_8);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, SSO_A2_Steps.STEP_11);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_C_channel_ROLE_I_Client_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, SSO_A2_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_0:
                
				URI = s.getNonce();
				s.Send(s.encrypt(s.sign(new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_SP"),URI)),aliases.get("ROLE_SP")));

                break;
                
            case STEP_3:
                
				VAR_C_R3 = (Crypto_SealedPair) s.Receive();
				VAR_C_DDCR3INVPCSSP = (AnBx_Params) s.verify((SignedObject) s.decrypt(VAR_C_R3),aliases.get("ROLE_SP"));
				eqCheck("3.1",aliases.get("ROLE_C"),(String) VAR_C_DDCR3INVPCSSP.getValue(0));
				eqCheck("3.2",aliases.get("ROLE_SP"),(String) VAR_C_DDCR3INVPCSSP.getValue(2));
				eqCheck("3.3",aliases.get("ROLE_idp"),(String) VAR_C_DDCR3INVPCSSP.getValue(1));
				eqCheck("3.4",URI,(Crypto_ByteArray) VAR_C_DDCR3INVPCSSP.getValue(4));

                break;
                
            case STEP_4:
                
				s.Send(s.encrypt(s.sign(new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_idp"),aliases.get("ROLE_SP"),(Crypto_ByteArray) VAR_C_DDCR3INVPCSSP.getValue(3),URI)),aliases.get("ROLE_idp")));

                break;
                
            case STEP_7:
                
				VAR_C_R7 = (Crypto_SealedPair) s.Receive();
				VAR_C_DDCR7INVPCSIDP = (AnBx_Params) s.verify((SignedObject) s.decrypt(VAR_C_R7),aliases.get("ROLE_idp"));
				eqCheck("7.1",URI,(Crypto_ByteArray) VAR_C_DDCR7INVPCSIDP.getValue(1));
				VAR_C_J12CDDCR7INVPCSIDP = (SignedObject) VAR_C_DDCR7INVPCSIDP.getValue(0);
				eqCheck("7.2",(AnBx_Params) s.verify(VAR_C_J12CDDCR7INVPCSIDP,aliases.get("ROLE_idp")),new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_idp")));

                break;
                
            case STEP_8:
                
				s.Send(s.encrypt(s.sign(new AnBx_Params(VAR_C_J12CDDCR7INVPCSIDP,URI)),aliases.get("ROLE_SP")));

                break;
                
            case STEP_11:
                
				VAR_C_R11 = (Crypto_SealedPair) s.Receive();
				wffCheck("11.1",(Crypto_ByteArray) s.verify((SignedObject) s.decrypt(VAR_C_R11),aliases.get("ROLE_SP")));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}