# Protocol: AndrewSecureRPC
# Java Configuration File: "../../genAnBx/src/andrewsecurerpc/AndrewSecureRPC.properties"
# AnBx Compiler and Code Generator - Version 2025.09
# -----------------------------
# Roles/Share
# -----------------------------
ROLESHARE = ROLE_B
# Aliases for agents B,A from the point of view of ROLE_x
ROLE_B = alice,bob
ROLE_A = alice,bob
# -----------------------------
# Channels
# -----------------------------
# A -> B - 0.0.0.0 -> 0.0.0.0:55556
ROLE_B_channel_ROLE_A_Server_Insecure_role = Server
ROLE_B_channel_ROLE_A_Server_Insecure_host = 0.0.0.0
ROLE_B_channel_ROLE_A_Server_Insecure_port = 55556
ROLE_B_channel_ROLE_A_Server_Insecure_type = SSL_PLAIN
# B -> A - 0.0.0.0:55556 -> 0.0.0.0
ROLE_A_channel_ROLE_B_Client_Insecure_role = Client
ROLE_A_channel_ROLE_B_Client_Insecure_host = 127.0.0.1
ROLE_A_channel_ROLE_B_Client_Insecure_port = 55556
ROLE_A_channel_ROLE_B_Client_Insecure_type = SSL_PLAIN
# -----------------------------
# Paths
# -----------------------------
keypath = ../../keystore/
sharepath = ./
anbxjpath = ../../../AnBxJ
# -----------------------------
# Cryptographic Engine Settings
# -----------------------------
# Java Cryptography Architecture (JCA) Reference Guide:
# https://docs.oracle.com/en/java/javase/21/security/java-cryptography-architecture-jca-reference-guide.html
# 
#  To view the standard algorithm names for Java 21, visit:
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html
#
# Information about Bouncy Castle cryptographic specifications can be found at:
# https://www.bouncycastle.org/documentation/specification_interoperability/#algorithms-and-key-types
# https://github.com/bcgit/bc-java/blob/main/docs/specifications.html
#
# These parameters are used to generate the <protocolname>.properties file
# Note: Signature Algorithms and (Asymmetric Encryption) Cipher Algorithms
# are automatically detected from the keys used, which are pre-memorized in the keystore
#
# Symmetric cipher algorithm for static (pre-shared) keys
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#cipher-algorithm-names
cipherScheme = AES
# to test if Bouncy Castle Library is correctly installed
# cipherscheme = Camellia
# default cipher scheme for standard JDK
# cipherscheme = AES
# Key size (in bits) for static symmetric keys (if algorithm supports multiple sizes)
keySize = 256
# -----------------------------
# Symmetric cipher algorithm for ephemeral key generation (used during session)
keyGenerationScheme = AES
# Key size (in bits) for dynamically generated symmetric keys (if algorithm supports multiple sizes)
keyGenerationSize = 256
# -----------------------------
# Secret Key Factory algorithm used for Password-Based Encryption (PBE) dynamic symmetric key generation
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#secretkeyfactory-algorithms
keyGenerationSchemePBE = PBKDF2WithHmacSHA512
# -----------------------------
# Key Pair Generator algorithm for dynamic creation of asymmetric key pairs
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#keypairgenerator-algorithms
keyPairGenerationScheme = RSA
# Key length for dynamic creation of asymmetric key pairs
keyPairGenerationSize = 2048
# -----------------------------
# SecureRandom Number Generation Algorithm
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#securerandom-number-generation-algorithms
secureRandomAlgorithm = DRBG
# -----------------------------
# (H)MAC Algorithm, also used for hmac key generation
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#mac-algorithms
hMacAlgorithm = HmacSHA256
# Key length in bits for (H)MAC key generation  (if algorithm supports multiple sizes)
hMacKeySize = 256
# -----------------------------
# MessageDigest Algorithm (Hash)
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#messagedigest-algorithms
messageDigestAlgorithm = SHA-256
# MessageDigest Algorithm used for Signature, as a fallback <digest>with<encryption> if KeyTypeToSignature mapping does not exist
messageDigestSignatureAlgorithm = SHA256
# -----------------------------
# Key Agreement Algorithm, used for key exchange (e.g., Diffie-Hellman)
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#keyagreement-algorithms
keyAgreementAlgorithm = DH
# Key Pair Generation for Key Agreement Algorithm, used for key exchange (e.g., Diffie-Hellman)
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#keypairgenerator-algorithms
keyAgreementKeyPairGenerationScheme = DH
# Length in bits for modulus used in Diffie-Hellman key agreement
dhModulusSize = 4096
# The elliptic curve used for ECDH key agreement
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#parameterspec-names
ecGenParameterSpec = secp256r1
# -----------------------------
# Asymmetric encryption scheme block mode (experimental feature)
asymcipherSchemeBlock = RSA
# -----------------------------
# SSLContext Algorithm
sslContext = TLSv1.3
# -----------------------------
# Mapping of key types to cipher transformations
# Transformations (ciphers) used for encryption, including algorithm name, mode, and padding, separated by /
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#cipher-algorithm-names
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#cipher-algorithm-modes
# https://docs.oracle.com/en/java/javase/21/docs/specs/security/standard-names.html#cipher-algorithm-paddings
keyTypeToCipher = AES -> AES/CBC/PKCS5Padding, Blowfish -> Blowfish/CBC/PKCS5Padding, Camellia -> Camellia/CBC/PKCS7Padding, ChaCha -> ChaCha20-Poly1305, EC -> ECIESwithAES-GCM/256/NoPadding, ElGamal -> ElGamal/ECB/OAEPWithSHA-256AndMGF1Padding, RSA -> RSA/ECB/OAEPWithSHA-256AndMGF1Padding, X25519 -> ECDHwithX25519-KDF2-SHA256/AES-GCM/256/NoPadding, X448 -> ECDHwithX448-KDF2-SHA512/AES-GCM/256/NoPadding
# -----------------------------
# Mapping of key types to signature algorithms
keyTypeToSignature = DSA -> SHA256withDSA, EC -> SHA256withECDSA, Ed25519 -> Ed25519, Ed448 -> Ed448, RSA -> SHA256withRSA, RSASSA-PSS -> RSASSA-PSS
# -----------------------------
# Java Security provider: default uses the java.security settings (preferred option)
# Or select a specific provider (e.g., BC for Bouncy Castle)
securityProvider = default
# Optional: Specific Java Security providers for different schemes
# These settings will override the securityProvider value if uncommented
# cipherSchemeProvider = default
# keyGenerationSchemeProvider = default
# keyGenerationSchemePBEProvider = default
# keyPairGenerationSchemeProvider = default
# secureRandomProvider = default
# hmacProvider = default
# messageDigestProvider = default
# signatureProvider = default
# asymEncProvider = default
# keyAgreementProvider = default
# sslContextProvider = default
