/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-12 14:50:54.399215 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isopk2pmap_a2;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class ISOPK2PMAP_A2_ROLE_A extends AnB_Protocol<ISOPK2PMAP_A2_Steps,ISOPK2PMAP_A2_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray NxNA = null;
	private Crypto_ByteArray Text1 = null;
	private SignedObject VAR_A_R1 = null;
	private AnBx_Params VAR_A_DAR1SS = null;
	private Crypto_ByteArray VAR_A_R3 = null;
	private SignedObject VAR_A_R11 = null;
	private AnBx_Params VAR_A_DAR11SS = null;
	private AnBx_Params VAR_A_R13 = null;
	private AnBx_Params VAR_A_DJ22AR13J22DJ12AR13SS = null;
	
	
	public ISOPK2PMAP_A2_ROLE_A(ISOPK2PMAP_A2_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		ISOPK2PMAP_A2_ROLE_A.sessions = sessions;
		
		AnB_Session ROLE_A_channel_ROLE_I_Server_Insecure = lbs.get("ROLE_A_channel_ROLE_I_Server_Insecure");
        
		init();
		
        try {
            ROLE_A_channel_ROLE_I_Server_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);
				//SB modified: it participates in all sessions with separate behavior
				if(sessionID.get() % 2 != 0){
                	executeStep(ROLE_A_channel_ROLE_I_Server_Insecure, ISOPK2PMAP_A2_Steps.STEP_1);
                	executeStep(ROLE_A_channel_ROLE_I_Server_Insecure, ISOPK2PMAP_A2_Steps.STEP_2);
                	executeStep(ROLE_A_channel_ROLE_I_Server_Insecure, ISOPK2PMAP_A2_Steps.STEP_3);
                	executeStep(ROLE_A_channel_ROLE_I_Server_Insecure, ISOPK2PMAP_A2_Steps.STEP_4);
                }
                else{
                	executeStep(ROLE_A_channel_ROLE_I_Server_Insecure, ISOPK2PMAP_A2_Steps.STEP_11);
                	executeStep(ROLE_A_channel_ROLE_I_Server_Insecure, ISOPK2PMAP_A2_Steps.STEP_12);
                	executeStep(ROLE_A_channel_ROLE_I_Server_Insecure, ISOPK2PMAP_A2_Steps.STEP_13);
                	executeStep(ROLE_A_channel_ROLE_I_Server_Insecure, ISOPK2PMAP_A2_Steps.STEP_14);
                }
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_A_channel_ROLE_I_Server_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, ISOPK2PMAP_A2_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_1:
                
				VAR_A_R1 = (SignedObject) s.Receive();
				VAR_A_DAR1SS = (AnBx_Params) s.verify(VAR_A_R1,aliases.get("ROLE_s"));
				eqCheck("1.1",VAR_A_DAR1SS,new AnBx_Params(aliases.get("ROLE_A"),s.getPublicKey(aliases.get("ROLE_A"),Crypto_KeyStoreType.sk())));

                break;
                
            case STEP_2:
                
				s.Send(empty);

                break;
                
            case STEP_3:
                
				VAR_A_R3 = (Crypto_ByteArray) s.Receive();
				eqCheck("3.1",empty,VAR_A_R3);

                break;
                
            case STEP_4:
                //SB: reordenada la generación de nonces, primero el que interesa
                Text1 = s.getNonce();
				NxNA = s.getNonce();			
				s.Send(new AnBx_Params(VAR_A_R1,s.sign(new AnBx_Params(NxNA,aliases.get("ROLE_B"),Text1))));

                break;
                
            case STEP_11:
                
				VAR_A_R11 = (SignedObject) s.Receive();
				VAR_A_DAR11SS = (AnBx_Params) s.verify(VAR_A_R11,aliases.get("ROLE_s"));
				eqCheck("11.1",aliases.get("ROLE_A"),(String) VAR_A_DAR11SS.getValue(0));
				eqCheck("11.2",(PublicKey) VAR_A_DAR11SS.getValue(1),(PublicKey) VAR_A_DAR1SS.getValue(1));

                break;
                
            case STEP_12:
                
				s.Send(empty);

                break;
                
            case STEP_13:
                
				VAR_A_R13 = (AnBx_Params) s.Receive();
				VAR_A_DJ22AR13J22DJ12AR13SS = (AnBx_Params) s.verify((SignedObject) VAR_A_R13.getValue(1),(PublicKey) new AnBx_Params((AnBx_Params) s.verify((SignedObject) VAR_A_R13.getValue(0),aliases.get("ROLE_s"))).getValue(1));
				eqCheck("13.1",aliases.get("ROLE_A"),(String) VAR_A_DJ22AR13J22DJ12AR13SS.getValue(1));
				eqCheck("13.2",aliases.get("ROLE_B"),(String) new AnBx_Params((AnBx_Params) s.verify((SignedObject) VAR_A_R13.getValue(0),aliases.get("ROLE_s"))).getValue(0));
				eqCheck("13.3",VAR_A_DAR11SS,new AnBx_Params(aliases.get("ROLE_A"),s.getPublicKey(aliases.get("ROLE_A"),Crypto_KeyStoreType.sk())));

                break;
                
            case STEP_14:
                
				//s.Send(new AnBx_Params(VAR_A_R11,s.sign(new AnBx_Params((Crypto_ByteArray) VAR_A_DJ22AR13J22DJ12AR13SS.getValue(0),aliases.get("ROLE_B"),(Crypto_ByteArray) VAR_A_DJ22AR13J22DJ12AR13SS.getValue(2)))));
				//SB: modified
				Text1 = s.getNonce(); // this should be "Text3"
				NxNA = s.getNonce(); // this should be "NxNB"
				s.Send(new AnBx_Params(VAR_A_R11,s.sign(new AnBx_Params(NxNA,aliases.get("ROLE_B"),Text1))));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}