/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-12 14:50:54.399215 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isopk2pmap_a2;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class ISOPK2PMAP_A2_ROLE_I extends AnB_Protocol<ISOPK2PMAP_A2_Steps,ISOPK2PMAP_A2_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	
	// local vars
	private SignedObject VAR_I_R0 = null;
	private Crypto_ByteArray VAR_I_R2 = null;
	private AnBx_Params VAR_I_R4 = null;
	private SignedObject VAR_I_R6 = null;
	private SignedObject VAR_I_J22IR4 = null;
	private Crypto_ByteArray VAR_I_R8 = null;
	private AnBx_Params VAR_I_R10 = null;
	private Crypto_ByteArray VAR_I_R12 = null;
	private SignedObject VAR_I_J22IR10 = null;
	private AnBx_Params VAR_I_R14 = null;
	
	
	public ISOPK2PMAP_A2_ROLE_I(ISOPK2PMAP_A2_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		ISOPK2PMAP_A2_ROLE_I.sessions = sessions;
		
		AnB_Session ROLE_I_channel_ROLE_s_Server_Insecure = lbs.get("ROLE_I_channel_ROLE_s_Server_Insecure");
        AnB_Session ROLE_I_channel_ROLE_A_Client_Insecure = lbs.get("ROLE_I_channel_ROLE_A_Client_Insecure");
        AnB_Session ROLE_I_channel_ROLE_B_Client_Insecure = lbs.get("ROLE_I_channel_ROLE_B_Client_Insecure");
        
		init();
		
        try {
            ROLE_I_channel_ROLE_s_Server_Insecure.Open();
            ROLE_I_channel_ROLE_A_Client_Insecure.Open();
            ROLE_I_channel_ROLE_B_Client_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);
				//SB modified: it participates in all sessions with separate behavior
				if(sessionID.get() % 2 != 0){
                	executeStep(ROLE_I_channel_ROLE_s_Server_Insecure, ISOPK2PMAP_A2_Steps.STEP_0);
                	executeStep(ROLE_I_channel_ROLE_A_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_1);
                	executeStep(ROLE_I_channel_ROLE_A_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_2);
                	executeStep(ROLE_I_channel_ROLE_A_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_3);
                	executeStep(ROLE_I_channel_ROLE_A_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_4);
                	executeStep(ROLE_I_channel_ROLE_s_Server_Insecure, ISOPK2PMAP_A2_Steps.STEP_5);
                	executeStep(ROLE_I_channel_ROLE_s_Server_Insecure, ISOPK2PMAP_A2_Steps.STEP_6);
                	executeStep(ROLE_I_channel_ROLE_B_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_7);
                	executeStep(ROLE_I_channel_ROLE_B_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_8);
                	executeStep(ROLE_I_channel_ROLE_B_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_9);
                	executeStep(ROLE_I_channel_ROLE_B_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_10);
                }
                else{
                	executeStep(ROLE_I_channel_ROLE_A_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_11);
                	executeStep(ROLE_I_channel_ROLE_A_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_12);
                	executeStep(ROLE_I_channel_ROLE_A_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_13);
                	executeStep(ROLE_I_channel_ROLE_A_Client_Insecure, ISOPK2PMAP_A2_Steps.STEP_14);
                }
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_I_channel_ROLE_s_Server_Insecure.Close();
		    ROLE_I_channel_ROLE_A_Client_Insecure.Close();
		    ROLE_I_channel_ROLE_B_Client_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, ISOPK2PMAP_A2_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_0:
                
				VAR_I_R0 = (SignedObject) s.Receive();
				wffCheck("0.1",VAR_I_R0);

                break;
                
            case STEP_1:
                
				s.Send(VAR_I_R0);

                break;
                
            case STEP_2:
                
				VAR_I_R2 = (Crypto_ByteArray) s.Receive();
				wffCheck("2.1",VAR_I_R2);

                break;
                
            case STEP_3:
                
				s.Send(VAR_I_R2);

                break;
                
            case STEP_4:
                
				VAR_I_R4 = (AnBx_Params) s.Receive();

                break;
                
            case STEP_5:
                
				s.Send(VAR_I_R2);

                break;
                
            case STEP_6:
                
				VAR_I_R6 = (SignedObject) s.Receive();
				wffCheck("6.1",VAR_I_R6);
				VAR_I_J22IR4 = (SignedObject) VAR_I_R4.getValue(1);
				wffCheck("6.2",VAR_I_J22IR4);

                break;
                
            case STEP_7:
                
				s.Send(VAR_I_R6);

                break;
                
            case STEP_8:
                
				VAR_I_R8 = (Crypto_ByteArray) s.Receive();
				eqCheck("8.1",VAR_I_R8,VAR_I_R2);

                break;
                
            case STEP_9:
                
				s.Send(new AnBx_Params(VAR_I_R0,VAR_I_J22IR4));

                break;
                
            case STEP_10:
                
				VAR_I_R10 = (AnBx_Params) s.Receive();
				wffCheck("10.1",VAR_I_R8);

                break;
                
            case STEP_11:
                
				s.Send(VAR_I_R0);

                break;
                
            case STEP_12:
                
				VAR_I_R12 = (Crypto_ByteArray) s.Receive();
				VAR_I_J22IR10 = (SignedObject) VAR_I_R10.getValue(1);
				wffCheck("12.1",VAR_I_J22IR10);
				eqCheck("12.2",VAR_I_R8,VAR_I_R12);

                break;
                
            case STEP_13:
                
				s.Send(new AnBx_Params(VAR_I_R6,VAR_I_J22IR10));

                break;
                
            case STEP_14:
                
				VAR_I_R14 = (AnBx_Params) s.Receive();

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}