/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 11:20:23.369801 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package kerberos_a;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class Kerberos_A_ROLE_I extends AnB_Protocol<Kerberos_A_Steps,Kerberos_A_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	private static Crypto_ByteArray tag = new Crypto_ByteArray("tag".getBytes());
	
	// local vars
	private Crypto_ByteArray X307_1 = null;
	private Crypto_ByteArray X307_2 = null;
	private Crypto_ByteArray X307_3 = null;
	private Crypto_ByteArray X405_5 = null;
	private Crypto_ByteArray X510_4 = null;
	private Crypto_ByteArray X512 = null;
	private Crypto_ByteArray Payload2 = null;
	private Crypto_KeyPair X307_Key = null;
	private SecretKey X405_Key = null;
	private SecretKey X405_4 = null;
	private SecretKey X510_Key = null;
	private SecretKey X510_3 = null;
	private SecretKey X511 = null;
	private AnBx_Params VAR_I_R0 = null;
	private String VAR_I_J14IR0 = null;
	private Crypto_ByteArray VAR_I_J23DJ44IR0SJ14IR0 = null;
	private Crypto_ByteArray VAR_I_J33DJ44IR0SJ14IR0 = null;
	private Crypto_ByteArray VAR_I_J34IR0 = null;
	private AnBx_Params VAR_I_R2 = null;
	private AnBx_Params VAR_I_DJ44IR2INVPI = null;
	private AnBx_Params VAR_I_DSJ34IR2DJ22DJ44IR2INVPISATH = null;
	private SecretKey VAR_I_J24IDSJ34IR2DJ22DJ44IR2INVPISATH = null;
	private Crypto_ByteArray VAR_I_J34IDSJ34IR2DJ22DJ44IR2INVPISATH = null;
	private AnBx_Params VAR_I_R4 = null;
	private String VAR_I_J12DSJ44IR4IJ24IDSJ34IR2DJ22DJ44IR2INVPISATH = null;
	private Crypto_ByteArray VAR_I_J24IR4 = null;
	private AnBx_Params VAR_I_R6 = null;
	private String VAR_I_J12DSJ22IR6X511 = null;
	private Crypto_ByteArray VAR_I_HX512 = null;
	
	
	public Kerberos_A_ROLE_I(Kerberos_A_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		Kerberos_A_ROLE_I.sessions = sessions;
		
		AnB_Session ROLE_I_channel_ROLE_C_Server_Insecure = lbs.get("ROLE_I_channel_ROLE_C_Server_Insecure");
        AnB_Session ROLE_I_channel_ROLE_ath_Client_Insecure = lbs.get("ROLE_I_channel_ROLE_ath_Client_Insecure");
        
		init();
		
        try {
            ROLE_I_channel_ROLE_C_Server_Insecure.Open();
            ROLE_I_channel_ROLE_ath_Client_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, Kerberos_A_Steps.STEP_0);
                executeStep(ROLE_I_channel_ROLE_ath_Client_Insecure, Kerberos_A_Steps.STEP_1);
                executeStep(ROLE_I_channel_ROLE_ath_Client_Insecure, Kerberos_A_Steps.STEP_2);
                executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, Kerberos_A_Steps.STEP_3);
                executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, Kerberos_A_Steps.STEP_4);
                executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, Kerberos_A_Steps.STEP_5);
                executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, Kerberos_A_Steps.STEP_6);
                executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, Kerberos_A_Steps.STEP_7);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_I_channel_ROLE_C_Server_Insecure.Close();
		    ROLE_I_channel_ROLE_ath_Client_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, Kerberos_A_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_0:
                
				VAR_I_R0 = (AnBx_Params) s.Receive();
				eqCheck("0.1",aliases.get("ROLE_gw"),(String) VAR_I_R0.getValue(1));
				VAR_I_J14IR0 = (String) VAR_I_R0.getValue(0);
				VAR_I_J23DJ44IR0SJ14IR0 = (Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.verify((SignedObject) VAR_I_R0.getValue(3),s.getPublicKey(VAR_I_J14IR0,Crypto_KeyStoreType.sk()))).getValue(1);
				VAR_I_J33DJ44IR0SJ14IR0 = (Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.verify((SignedObject) VAR_I_R0.getValue(3),s.getPublicKey(VAR_I_J14IR0,Crypto_KeyStoreType.sk()))).getValue(2);
				eqCheck("0.2",VAR_I_J33DJ44IR0SJ14IR0,s.makeDigest(new AnBx_Params(VAR_I_J14IR0,aliases.get("ROLE_gw"),VAR_I_J23DJ44IR0SJ14IR0)));
				VAR_I_J34IR0 = (Crypto_ByteArray) VAR_I_R0.getValue(2);
				eqCheck("0.3",VAR_I_J34IR0,VAR_I_J23DJ44IR0SJ14IR0);

                break;
                
            case STEP_1:
                
				X307_1 = s.getNonce();
				X307_2 = s.getNonce();
				X307_3 = s.getNonce();
				X307_Key = s.getKeyPair();
				s.Send(new AnBx_Params(aliases.get("ROLE_I"),aliases.get("ROLE_gw"),VAR_I_J34IR0,s.encrypt(new AnBx_Params(X307_1,X307_2,s.makeDigest(X307_3)),X307_Key.getPublicKey())));

                break;
                
            case STEP_2:
                
				VAR_I_R2 = (AnBx_Params) s.Receive();
				eqCheck("2.1",aliases.get("ROLE_I"),(String) VAR_I_R2.getValue(0));
				VAR_I_DJ44IR2INVPI = (AnBx_Params) s.decrypt((Crypto_SealedPair) VAR_I_R2.getValue(3));
				VAR_I_DSJ34IR2DJ22DJ44IR2INVPISATH = (AnBx_Params) s.decrypt((SealedObject) VAR_I_R2.getValue(2),(SecretKey) s.verify((SignedObject) VAR_I_DJ44IR2INVPI.getValue(1),aliases.get("ROLE_ath")));
				eqCheck("2.2",aliases.get("ROLE_gw"),(String) VAR_I_DSJ34IR2DJ22DJ44IR2INVPISATH.getValue(0));
				eqCheck("2.3",tag,(Crypto_ByteArray) VAR_I_DJ44IR2INVPI.getValue(0));
				eqCheck("2.4",VAR_I_J23DJ44IR0SJ14IR0,(Crypto_ByteArray) VAR_I_DSJ34IR2DJ22DJ44IR2INVPISATH.getValue(3));

                break;
                
            case STEP_3:
                
				X405_5 = s.getNonce();
				X405_Key = s.getSymmetricKey();
				X405_4 = s.getSymmetricKey();
				VAR_I_J24IDSJ34IR2DJ22DJ44IR2INVPISATH = (SecretKey) VAR_I_DSJ34IR2DJ22DJ44IR2INVPISATH.getValue(1);
				VAR_I_J34IDSJ34IR2DJ22DJ44IR2INVPISATH = (Crypto_ByteArray) VAR_I_DSJ34IR2DJ22DJ44IR2INVPISATH.getValue(2);
				s.Send(new AnBx_Params(VAR_I_J14IR0,s.encrypt(new AnBx_Params(aliases.get("ROLE_I"),aliases.get("ROLE_I"),aliases.get("ROLE_I"),X405_4,X405_5),X405_Key),s.encrypt(new AnBx_Params(aliases.get("ROLE_gw"),VAR_I_J24IDSJ34IR2DJ22DJ44IR2INVPISATH,VAR_I_J34IDSJ34IR2DJ22DJ44IR2INVPISATH,VAR_I_J34IR0),(SecretKey) s.verify((SignedObject) VAR_I_DJ44IR2INVPI.getValue(1),aliases.get("ROLE_ath"))),s.encrypt(new AnBx_Params(tag,(SignedObject) VAR_I_DJ44IR2INVPI.getValue(1)),s.getPublicKey(VAR_I_J14IR0,Crypto_KeyStoreType.pk()))));

                break;
                
            case STEP_4:
                
				VAR_I_R4 = (AnBx_Params) s.Receive();
				eqCheck("4.1",aliases.get("ROLE_s"),(String) VAR_I_R4.getValue(0));
				VAR_I_J12DSJ44IR4IJ24IDSJ34IR2DJ22DJ44IR2INVPISATH = (String) new AnBx_Params((AnBx_Params) s.decrypt((SealedObject) VAR_I_R4.getValue(3),VAR_I_J24IDSJ34IR2DJ22DJ44IR2INVPISATH)).getValue(0);
				eqCheck("4.2",VAR_I_J14IR0,VAR_I_J12DSJ44IR4IJ24IDSJ34IR2DJ22DJ44IR2INVPISATH);
				eqCheck("4.3",VAR_I_J33DJ44IR0SJ14IR0,s.makeDigest(new AnBx_Params(VAR_I_J14IR0,aliases.get("ROLE_gw"),VAR_I_J23DJ44IR0SJ14IR0)));
				eqCheck("4.4",VAR_I_J34IDSJ34IR2DJ22DJ44IR2INVPISATH,(Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt((SealedObject) VAR_I_R4.getValue(3),VAR_I_J24IDSJ34IR2DJ22DJ44IR2INVPISATH)).getValue(1));
				eqCheck("4.5",(AnBx_Params) s.decrypt((SealedObject) VAR_I_R4.getValue(2),X405_Key),new AnBx_Params(aliases.get("ROLE_I"),aliases.get("ROLE_I"),aliases.get("ROLE_I"),X405_4,X405_5));

                break;
                
            case STEP_5:
                
				X510_4 = s.getNonce();
				X512 = s.getNonce();
				X510_Key = s.getSymmetricKey();
				X510_3 = s.getSymmetricKey();
				X511 = s.getSymmetricKey();
				VAR_I_J24IR4 = (Crypto_ByteArray) VAR_I_R4.getValue(1);
				s.Send(new AnBx_Params(VAR_I_J14IR0,s.encrypt(new AnBx_Params(aliases.get("ROLE_I"),aliases.get("ROLE_I"),X510_3,X510_4),X510_Key),s.encrypt(new AnBx_Params(aliases.get("ROLE_s"),X511,X512,VAR_I_J24IR4),VAR_I_J24IDSJ34IR2DJ22DJ44IR2INVPISATH)));

                break;
                
            case STEP_6:
                
				VAR_I_R6 = (AnBx_Params) s.Receive();
				wffCheck("6.1",VAR_I_J24IR4);
				wffCheck("6.2",VAR_I_J34IDSJ34IR2DJ22DJ44IR2INVPISATH);
				VAR_I_J12DSJ22IR6X511 = (String) new AnBx_Params((AnBx_Params) s.decrypt((SealedObject) VAR_I_R6.getValue(1),X511)).getValue(0);
				eqCheck("6.3",VAR_I_J14IR0,VAR_I_J12DSJ22IR6X511);
				eqCheck("6.4",VAR_I_J33DJ44IR0SJ14IR0,s.makeDigest(new AnBx_Params(VAR_I_J14IR0,aliases.get("ROLE_gw"),VAR_I_J23DJ44IR0SJ14IR0)));
				eqCheck("6.5",(AnBx_Params) s.decrypt((SealedObject) VAR_I_R6.getValue(0),X510_Key),new AnBx_Params(aliases.get("ROLE_I"),aliases.get("ROLE_I"),X510_3,X510_4));
				VAR_I_HX512 = s.makeDigest(X512);
				eqCheck("6.6",VAR_I_HX512,(Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt((SealedObject) VAR_I_R6.getValue(1),X511)).getValue(1));

                break;
                
            case STEP_7:
                
				Payload2 = s.getNonce();
				s.Send(new AnBx_Params(s.encrypt(VAR_I_HX512,X511),s.encrypt(new AnBx_Params(tag,Payload2),X511)));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}