/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 11:20:23.369801 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package kerberos_a;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class Kerberos_A_ROLE_C extends AnB_Protocol<Kerberos_A_Steps,Kerberos_A_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	private static Crypto_ByteArray tag = new Crypto_ByteArray("tag".getBytes());
	
	// local vars
	private Crypto_ByteArray N1 = null;
	private Crypto_ByteArray N2 = null;
	private Crypto_ByteArray T0 = null;
	private AnBx_Params VAR_C_R3 = null;
	private AnBx_Params VAR_C_DSJ34CR3DJ22DJ44CR3INVPCSATH = null;
	private SecretKey VAR_C_J24CDSJ34CR3DJ22DJ44CR3INVPCSATH = null;
	private AnBx_Params VAR_C_R5 = null;
	private AnBx_Params VAR_C_DSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH = null;
	private Crypto_ByteArray VAR_C_HJ34CDSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH = null;
	private SecretKey VAR_C_J24CDSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH = null;
	private AnBx_Params VAR_C_R7 = null;
	
	
	public Kerberos_A_ROLE_C(Kerberos_A_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		Kerberos_A_ROLE_C.sessions = sessions;
		
		AnB_Session ROLE_C_channel_ROLE_I_Client_Insecure = lbs.get("ROLE_C_channel_ROLE_I_Client_Insecure");
        
		init();
		
        try {
            ROLE_C_channel_ROLE_I_Client_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, Kerberos_A_Steps.STEP_0);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, Kerberos_A_Steps.STEP_3);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, Kerberos_A_Steps.STEP_4);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, Kerberos_A_Steps.STEP_5);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, Kerberos_A_Steps.STEP_6);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, Kerberos_A_Steps.STEP_7);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_C_channel_ROLE_I_Client_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, Kerberos_A_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_0:
                
				N1 = s.getNonce();
				T0 = s.getNonce();
				s.Send(new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_gw"),N1,s.sign(new AnBx_Params(T0,N1,s.makeDigest(new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_gw"),N1))))));

                break;
                
            case STEP_3:
                
				VAR_C_R3 = (AnBx_Params) s.Receive();
				eqCheck("3.1",aliases.get("ROLE_C"),(String) VAR_C_R3.getValue(0));
				VAR_C_DSJ34CR3DJ22DJ44CR3INVPCSATH = (AnBx_Params) s.decrypt((SealedObject) VAR_C_R3.getValue(2),(SecretKey) s.verify((SignedObject) new AnBx_Params((AnBx_Params) s.decrypt((Crypto_SealedPair) VAR_C_R3.getValue(3))).getValue(1),aliases.get("ROLE_ath")));
				eqCheck("3.2",aliases.get("ROLE_gw"),(String) VAR_C_DSJ34CR3DJ22DJ44CR3INVPCSATH.getValue(0));
				eqCheck("3.3",N1,(Crypto_ByteArray) VAR_C_DSJ34CR3DJ22DJ44CR3INVPCSATH.getValue(3));
				eqCheck("3.4",tag,(Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt((Crypto_SealedPair) VAR_C_R3.getValue(3))).getValue(0));

                break;
                
            case STEP_4:
                
				N2 = s.getNonce();
				VAR_C_J24CDSJ34CR3DJ22DJ44CR3INVPCSATH = (SecretKey) VAR_C_DSJ34CR3DJ22DJ44CR3INVPCSATH.getValue(1);
				s.Send(new AnBx_Params(aliases.get("ROLE_s"),N2,(SealedObject) VAR_C_R3.getValue(1),s.encrypt(new AnBx_Params(aliases.get("ROLE_C"),(Crypto_ByteArray) VAR_C_DSJ34CR3DJ22DJ44CR3INVPCSATH.getValue(2)),VAR_C_J24CDSJ34CR3DJ22DJ44CR3INVPCSATH)));

                break;
                
            case STEP_5:
                
				VAR_C_R5 = (AnBx_Params) s.Receive();
				eqCheck("5.1",aliases.get("ROLE_C"),(String) VAR_C_R5.getValue(0));
				VAR_C_DSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH = (AnBx_Params) s.decrypt((SealedObject) VAR_C_R5.getValue(2),VAR_C_J24CDSJ34CR3DJ22DJ44CR3INVPCSATH);
				eqCheck("5.2",aliases.get("ROLE_s"),(String) VAR_C_DSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH.getValue(0));
				eqCheck("5.3",N2,(Crypto_ByteArray) VAR_C_DSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH.getValue(3));

                break;
                
            case STEP_6:
                
				VAR_C_HJ34CDSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH = s.makeDigest((Crypto_ByteArray) VAR_C_DSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH.getValue(2));
				VAR_C_J24CDSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH = (SecretKey) VAR_C_DSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH.getValue(1);
				s.Send(new AnBx_Params((SealedObject) VAR_C_R5.getValue(1),s.encrypt(new AnBx_Params(aliases.get("ROLE_C"),VAR_C_HJ34CDSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH),VAR_C_J24CDSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH)));

                break;
                
            case STEP_7:
                
				VAR_C_R7 = (AnBx_Params) s.Receive();
				eqCheck("7.1",tag,(Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt((SealedObject) VAR_C_R7.getValue(1),VAR_C_J24CDSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH)).getValue(0));
				eqCheck("7.2",VAR_C_HJ34CDSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH,(Crypto_ByteArray) s.decrypt((SealedObject) VAR_C_R7.getValue(0),VAR_C_J24CDSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH));
				//SB: added to log the recovery of Payload2
				wffCheck("7.3",(Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt((SealedObject) VAR_C_R7.getValue(1),VAR_C_J24CDSJ33CR5CJ24CDSJ34CR3DJ22DJ44CR3INVPCSATH)).getValue(1));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}