/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 11:20:23.369801 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package kerberos_a;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class Kerberos_A_ROLE_ath extends AnB_Protocol<Kerberos_A_Steps,Kerberos_A_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	private static Crypto_ByteArray tag = new Crypto_ByteArray("tag".getBytes());
	
	// local vars
	private SecretKey ShkAthgw = null;
	private SecretKey KCG = null;
	private SecretKey Ktemp = null;
	private Crypto_ByteArray T1 = null;
	private AnBx_Params VAR_ATH_R1 = null;
	
	
	public Kerberos_A_ROLE_ath(Kerberos_A_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkAthgw = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_ath")+"_"+aliases.get("ROLE_gw")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		Kerberos_A_ROLE_ath.sessions = sessions;
		
		AnB_Session ROLE_ath_channel_ROLE_I_Server_Insecure = lbs.get("ROLE_ath_channel_ROLE_I_Server_Insecure");
        
		init();
		
        try {
            ROLE_ath_channel_ROLE_I_Server_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_ath_channel_ROLE_I_Server_Insecure, Kerberos_A_Steps.STEP_1);
                executeStep(ROLE_ath_channel_ROLE_I_Server_Insecure, Kerberos_A_Steps.STEP_2);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_ath_channel_ROLE_I_Server_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, Kerberos_A_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_1:
                
				VAR_ATH_R1 = (AnBx_Params) s.Receive();
				eqCheck("1.1",aliases.get("ROLE_I"),(String) VAR_ATH_R1.getValue(0));
				eqCheck("1.2",aliases.get("ROLE_gw"),(String) VAR_ATH_R1.getValue(1));

                break;
                
            case STEP_2:
                
				KCG = s.getSymmetricKey();
				Ktemp = s.getSymmetricKey();
				T1 = s.getNonce();
				s.Send(new AnBx_Params(aliases.get("ROLE_I"),s.encrypt(new AnBx_Params(aliases.get("ROLE_ath"),aliases.get("ROLE_I"),aliases.get("ROLE_gw"),KCG,T1),ShkAthgw),s.encrypt(new AnBx_Params(aliases.get("ROLE_gw"),KCG,T1,(Crypto_ByteArray) VAR_ATH_R1.getValue(2)),Ktemp),s.encrypt(new AnBx_Params(tag,s.sign(Ktemp)),aliases.get("ROLE_I"))));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}