
/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 11:20:23.369801 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package kerberos_a;

import anbxj.AnBx_CommandLine_Parser;
import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.Channel_Settings;

import java.util.HashMap;
import java.util.Map;

public final class Kerberos_A_CommandLine_Parser extends AnBx_CommandLine_Parser<Kerberos_A_Roles,Kerberos_A_Channels> {

	public Kerberos_A_CommandLine_Parser(String[] args, String prot) {
		super(args, prot, prot, Kerberos_A_Roles.class, true);
		// AnBx_Debug.setAPPLICATION(true);
		// AnBx_Debug.setPROTOCOL(true);
		// AnBx_Debug.setSESSION(true);
		// AnBx_Debug.setLANGUAGE(true);
		// AnBx_Debug.setENCRYPTION(true);
		// AnBx_Debug.setBUSINESS_LOGIC(true);
		// AnBx_Debug.setALL(true);
    		initProtocol();
	}

	protected void initProtocol() {

		Map<String, Channel_Settings> cs = new HashMap<String, Channel_Settings>();
		Map<String, String> aliases = new HashMap<String, String>();
		Kerberos_A_Principal Kerberos_A_pr = null;
        if (role == null) terminate("no or incorrect role specified");
		AnBx_Debug.setAppname(role.toString());
		initRole(ct, role, cs, aliases, Kerberos_A_Roles.class, Kerberos_A_Channels.class);
		AnBx_Debug.out(layer, "myRole: " + role);
        AnBx_Debug.out(layer, "sessions: " + sessions);

		if (myAlias != null && keypath != null && sharepath != null) {
			switch (role) {
			case ROLE_I:
				Kerberos_A_pr = new Kerberos_A_Principal(myAlias, keypath, cs, aliases, true, crypto_config);
                Kerberos_A_pr.run(new Kerberos_A_ROLE_I(role, protname, sharepath), sessions);
				break;
			case ROLE_ath:
				Kerberos_A_pr = new Kerberos_A_Principal(myAlias, keypath, cs, aliases, true, crypto_config);
                Kerberos_A_pr.run(new Kerberos_A_ROLE_ath(role, protname, sharepath), sessions);
				break;
			case ROLE_C:
				Kerberos_A_pr = new Kerberos_A_Principal(myAlias, keypath, cs, aliases, true, crypto_config);
                Kerberos_A_pr.run(new Kerberos_A_ROLE_C(role, protname, sharepath), sessions);
				break;
			
            default:
				break;
			}
		} else terminate("Unable to initialize " + protname + " Principal");
	}
}