/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 10:37:34.46968 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isosk2pmap_a2;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnBx_CommandLine_Parser;
import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.Crypto_Config;
import anbxj.Crypto_KeyMode;

public class ISOSK2PMAP_A2_Setup extends AnBx_CommandLine_Parser<ISOSK2PMAP_A2_Roles, ISOSK2PMAP_A2_Channels> {

	public static void main(String[] args) {

		// AnBx_Debug.setAPPLICATION(true);
		// AnBx_Debug.setPROTOCOL(true);
		// AnBx_Debug.setSESSION(true);
		// AnBx_Debug.setLANGUAGE(true);
		// AnBx_Debug.setENCRYPTION(true);
		// AnBx_Debug.setBUSINESS_LOGIC(true);
		// AnBx_Debug.setALL(true); // true only for testing speed

		long start = System.nanoTime();

		ISOSK2PMAP_A2_Setup p = new ISOSK2PMAP_A2_Setup(args, ISOSK2PMAP_A2_Setup.class.getSimpleName(), ISOSK2PMAP_A2.class.getSimpleName(), true, false);
		p.setLayer(AnBx_Layers.APPLICATION);
		p.initProtocol();
		
		long end = System.nanoTime();
      	double durationInMs = (end - start) / 1_000_000.0;
		System.out.println(String.format("%s - Execution time was %.3f ms.", "ISOSK2PMAP_A2_Setup", durationInMs));
	}

	public ISOSK2PMAP_A2_Setup(String[] args, String prot, String configName, boolean vflag, boolean parseFullArgs) {
	 	super(args, prot, configName, ISOSK2PMAP_A2_Roles.class, vflag, parseFullArgs);
	}

	@Override
	protected void initProtocol() {
		Map<String, String> aliases = new HashMap<String, String>();
		ISOSK2PMAP_A2_Roles roleshare = getRoleShare(ISOSK2PMAP_A2_Roles.class);
		readConfigFile(aliases, ISOSK2PMAP_A2_Roles.class, roleshare);

		AnB_Crypto_Wrapper s;
        s = new AnB_Crypto_Wrapper(myAlias,new Crypto_Config(configFile));

        // create shared knowledge objects
		 createSharedObject(s.getSymmetricKey(Crypto_KeyMode.PRESHARED), Arrays.asList(ISOSK2PMAP_A2_Roles.ROLE_A, ISOSK2PMAP_A2_Roles.ROLE_B), Arrays.asList(ISOSK2PMAP_A2_Roles.ROLE_A, ISOSK2PMAP_A2_Roles.ROLE_B), "shk", ".ser");
		
        
        // create agreed knowledge objects
		
	}

	void createSharedObject(Object obj, List<ISOSK2PMAP_A2_Roles> shroles, List<ISOSK2PMAP_A2_Roles> parroles, String filenameprefix, String ext) {
	    // Create the aliases map outside of the loop
	    Map<String, String> aliases = new HashMap<String, String>();

	    // Populate the aliases map for each role
	    for (ISOSK2PMAP_A2_Roles shrole : shroles) {
	        readConfigFile(aliases, ISOSK2PMAP_A2_Roles.class, shrole); // Pass enum type role
	        // Construct the filename using the aliases map
	        
		    StringBuilder filenameBuilder = new StringBuilder(filenameprefix);
		    if (!parroles.isEmpty()) {
		    	for (ISOSK2PMAP_A2_Roles parrole : parroles) {
		    		filenameBuilder.append("_").append(aliases.get(parrole.toString()));
		    	}	
		    }
            String filename = filenameBuilder.append(ext).toString();
	        AnB_Crypto_Wrapper.writeObject(obj, sharepath + filename);
	    }
	}

}