/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 10:37:34.46968 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isosk2pmap_a2;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;
//SB: Import random library
import java.util.Random;

public final class ISOSK2PMAP_A2_ROLE_I extends AnB_Protocol<ISOSK2PMAP_A2_Steps,ISOSK2PMAP_A2_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);
	// SB: Initializes a random number generator (for the last step)
	private static Random rand = new Random();

	// local knowledge - constants
	
	// local vars
	private SealedObject VAR_I_R0 = null;
	private SealedObject VAR_I_R2 = null;
	//SB: new variable to keep track of the previous session value
	private static SealedObject PREVIOUS_VAR_I_R2 = null;
	
	
	public ISOSK2PMAP_A2_ROLE_I(ISOSK2PMAP_A2_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		ISOSK2PMAP_A2_ROLE_I.sessions = sessions;
		
		AnB_Session ROLE_I_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_I_channel_ROLE_A_Server_Insecure");
        AnB_Session ROLE_I_channel_ROLE_B_Client_Insecure = lbs.get("ROLE_I_channel_ROLE_B_Client_Insecure");
        
		init();
		
        try {
            ROLE_I_channel_ROLE_A_Server_Insecure.Open();
            ROLE_I_channel_ROLE_B_Client_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_I_channel_ROLE_A_Server_Insecure, ISOSK2PMAP_A2_Steps.STEP_0);
                executeStep(ROLE_I_channel_ROLE_B_Client_Insecure, ISOSK2PMAP_A2_Steps.STEP_1);
                executeStep(ROLE_I_channel_ROLE_B_Client_Insecure, ISOSK2PMAP_A2_Steps.STEP_2);
                executeStep(ROLE_I_channel_ROLE_A_Server_Insecure, ISOSK2PMAP_A2_Steps.STEP_3);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_I_channel_ROLE_A_Server_Insecure.Close();
		    ROLE_I_channel_ROLE_B_Client_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, ISOSK2PMAP_A2_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_0:
                
				noteqCheck("0.2",aliases.get("ROLE_I"),aliases.get("ROLE_A"));
				noteqCheck("0.4",aliases.get("ROLE_I"),aliases.get("ROLE_B"));
				VAR_I_R0 = (SealedObject) s.Receive();
				wffCheck("0.1",VAR_I_R0);

                break;
                
            case STEP_1:
                
				s.Send(VAR_I_R0);

                break;
                
            case STEP_2:
                
				VAR_I_R2 = (SealedObject) s.Receive();
				wffCheck("2.1",VAR_I_R2);

                break;
                
            case STEP_3:
                
				//SB: Replay attack pattern
				double choose = rand.nextDouble();
				if (PREVIOUS_VAR_I_R2 == null || choose < 0.5){
					s.Send(VAR_I_R2);
					PREVIOUS_VAR_I_R2 = VAR_I_R2;
				}
				else{
					s.Send(PREVIOUS_VAR_I_R2);
				}

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}