/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-12 13:41:57.73216 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package nspk;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class NSPK_ROLE_B extends AnB_Protocol<NSPK_Steps,NSPK_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	
	// local vars
	private Crypto_ByteArray NxNB = null;
	private Crypto_SealedPair VAR_B_R0 = null;
	private AnBx_Params VAR_B_DBR0INVPB = null;
	private Crypto_SealedPair VAR_B_R2 = null;
	
	
	public NSPK_ROLE_B(NSPK_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		NSPK_ROLE_B.sessions = sessions;
		
		AnB_Session ROLE_B_channel_ROLE_A_Server_Insecure = lbs.get("ROLE_B_channel_ROLE_A_Server_Insecure");
        
		init();
		
        try {
            ROLE_B_channel_ROLE_A_Server_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, NSPK_Steps.STEP_0);
                executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, NSPK_Steps.STEP_1);
                executeStep(ROLE_B_channel_ROLE_A_Server_Insecure, NSPK_Steps.STEP_2);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_B_channel_ROLE_A_Server_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, NSPK_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_0:
                
				VAR_B_R0 = (Crypto_SealedPair) s.Receive();
				VAR_B_DBR0INVPB = (AnBx_Params) s.decrypt(VAR_B_R0);
				wffCheck("0.1",(String) VAR_B_DBR0INVPB.getValue(1));
				//SB: added to log the recovery of NxNA value
				wffCheck("0.2",(Crypto_ByteArray) VAR_B_DBR0INVPB.getValue(0));

                break;
                
            case STEP_1:
                
				NxNB = s.getNonce();
				s.Send(s.encrypt(new AnBx_Params((Crypto_ByteArray) VAR_B_DBR0INVPB.getValue(0),NxNB),s.getPublicKey((String) VAR_B_DBR0INVPB.getValue(1),Crypto_KeyStoreType.pk())));

                break;
                
            case STEP_2:
                
				VAR_B_R2 = (Crypto_SealedPair) s.Receive();
				eqCheck("2.1",NxNB,(Crypto_ByteArray) s.decrypt(VAR_B_R2));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}