/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 16:16:30.290123 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package sso_s;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class SSO_S_ROLE_C extends AnB_Protocol<SSO_S_Steps,SSO_S_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray URI = null;
	private Crypto_ByteArray ID = null;
	private Crypto_ByteArray Data = null;
	private AnBx_Params VAR_C_R1 = null;
	private Crypto_ByteArray VAR_C_J33CR1 = null;
	private AnBx_Params VAR_C_R3 = null;
	private Crypto_ByteArray VAR_C_J45CR3 = null;
	private Crypto_SealedPair VAR_C_R7 = null;
	private AnBx_Params VAR_C_DDCR7INVPCSIDP = null;
	private SignedObject VAR_C_J12CDDCR7INVPCSIDP = null;
	private AnBx_Params VAR_C_R9 = null;
	
	
	public SSO_S_ROLE_C(SSO_S_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		SSO_S_ROLE_C.sessions = sessions;
		
		AnB_Session ROLE_C_channel_ROLE_I_Client_Secure = lbs.get("ROLE_C_channel_ROLE_I_Client_Secure");
        AnB_Session ROLE_C_channel_ROLE_I_Server_Secure = lbs.get("ROLE_C_channel_ROLE_I_Server_Secure");
        AnB_Session ROLE_C_channel_ROLE_I_Client_Insecure = lbs.get("ROLE_C_channel_ROLE_I_Client_Insecure");
        
		init();
		
        try {
            ROLE_C_channel_ROLE_I_Client_Secure.Open();
            ROLE_C_channel_ROLE_I_Server_Secure.Open();
            ROLE_C_channel_ROLE_I_Client_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_C_channel_ROLE_I_Client_Secure, SSO_S_Steps.STEP_0);
                executeStep(ROLE_C_channel_ROLE_I_Server_Secure, SSO_S_Steps.STEP_1);
                executeStep(ROLE_C_channel_ROLE_I_Server_Secure, SSO_S_Steps.STEP_2);
                executeStep(ROLE_C_channel_ROLE_I_Client_Secure, SSO_S_Steps.STEP_3);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, SSO_S_Steps.STEP_4);
                executeStep(ROLE_C_channel_ROLE_I_Client_Insecure, SSO_S_Steps.STEP_7);
                executeStep(ROLE_C_channel_ROLE_I_Client_Secure, SSO_S_Steps.STEP_8);
                executeStep(ROLE_C_channel_ROLE_I_Server_Secure, SSO_S_Steps.STEP_9);
                executeStep(ROLE_C_channel_ROLE_I_Server_Secure, SSO_S_Steps.STEP_10);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_C_channel_ROLE_I_Client_Secure.Close();
		    ROLE_C_channel_ROLE_I_Server_Secure.Close();
		    ROLE_C_channel_ROLE_I_Client_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, SSO_S_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_0:
                
				URI = s.getNonce();
				s.Send(new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_I"),URI));

                break;
                
            case STEP_1:
                
				VAR_C_R1 = (AnBx_Params) s.Receive();
				eqCheck("1.1",aliases.get("ROLE_C"),(String) VAR_C_R1.getValue(0));
				eqCheck("1.2",aliases.get("ROLE_C"),(String) VAR_C_R1.getValue(1));

                break;
                
            case STEP_2:
                
				ID = s.getNonce();
				VAR_C_J33CR1 = (Crypto_ByteArray) VAR_C_R1.getValue(2);
				s.Send(new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_idp"),aliases.get("ROLE_C"),ID,VAR_C_J33CR1));

                break;
                
            case STEP_3:
                
				VAR_C_R3 = (AnBx_Params) s.Receive();
				wffCheck("3.1",VAR_C_J33CR1);
				eqCheck("3.2",aliases.get("ROLE_C"),(String) VAR_C_R3.getValue(0));
				eqCheck("3.3",aliases.get("ROLE_I"),(String) VAR_C_R3.getValue(2));
				eqCheck("3.4",aliases.get("ROLE_idp"),(String) VAR_C_R3.getValue(1));
				eqCheck("3.5",URI,(Crypto_ByteArray) VAR_C_R3.getValue(4));

                break;
                
            case STEP_4:
                
				VAR_C_J45CR3 = (Crypto_ByteArray) VAR_C_R3.getValue(3);
				s.Send(s.encrypt(s.sign(new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_idp"),aliases.get("ROLE_I"),VAR_C_J45CR3,URI)),aliases.get("ROLE_idp")));

                break;
                
            case STEP_7:
                
				VAR_C_R7 = (Crypto_SealedPair) s.Receive();
				wffCheck("7.1",VAR_C_J45CR3);
				VAR_C_DDCR7INVPCSIDP = (AnBx_Params) s.verify((SignedObject) s.decrypt(VAR_C_R7),aliases.get("ROLE_idp"));
				eqCheck("7.2",URI,(Crypto_ByteArray) VAR_C_DDCR7INVPCSIDP.getValue(1));
				VAR_C_J12CDDCR7INVPCSIDP = (SignedObject) VAR_C_DDCR7INVPCSIDP.getValue(0);
				eqCheck("7.3",(AnBx_Params) s.verify(VAR_C_J12CDDCR7INVPCSIDP,aliases.get("ROLE_idp")),new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_idp")));

                break;
                
            case STEP_8:
                
				s.Send(new AnBx_Params(VAR_C_J12CDDCR7INVPCSIDP,URI));

                break;
                
            case STEP_9:
                
				VAR_C_R9 = (AnBx_Params) s.Receive();
				eqCheck("9.1",VAR_C_J33CR1,(Crypto_ByteArray) VAR_C_R9.getValue(1));
				eqCheck("9.2",(AnBx_Params) s.verify((SignedObject) VAR_C_R9.getValue(0),aliases.get("ROLE_idp")),new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_idp")));

                break;
                
            case STEP_10:
                
				Data = s.getNonce();
				s.Send(Data);

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}