/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-12 13:42:28.346021 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package nspk_s_2;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class NSPK_S_2_ROLE_A extends AnB_Protocol<NSPK_S_2_Steps,NSPK_S_2_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	
	// local vars
	private Crypto_ByteArray NxNA = null;
	private Crypto_SealedPair VAR_A_R3 = null;
	private AnBx_Params VAR_A_DAR3INVPA = null;
	
	
	public NSPK_S_2_ROLE_A(NSPK_S_2_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		NSPK_S_2_ROLE_A.sessions = sessions;
		
		AnB_Session ROLE_A_channel_ROLE_I_Client_Insecure = lbs.get("ROLE_A_channel_ROLE_I_Client_Insecure");
        
		init();
		
        try {
            ROLE_A_channel_ROLE_I_Client_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_A_channel_ROLE_I_Client_Insecure, NSPK_S_2_Steps.STEP_0);
                executeStep(ROLE_A_channel_ROLE_I_Client_Insecure, NSPK_S_2_Steps.STEP_3);
                executeStep(ROLE_A_channel_ROLE_I_Client_Insecure, NSPK_S_2_Steps.STEP_4);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_A_channel_ROLE_I_Client_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, NSPK_S_2_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_0:
                
				NxNA = s.getNonce();
				s.Send(s.encrypt(new AnBx_Params(NxNA,aliases.get("ROLE_A")),aliases.get("ROLE_I")));

                break;
                
            case STEP_3:
                
				VAR_A_R3 = (Crypto_SealedPair) s.Receive();
				VAR_A_DAR3INVPA = (AnBx_Params) s.decrypt(VAR_A_R3);
				eqCheck("3.1",NxNA,(Crypto_ByteArray) VAR_A_DAR3INVPA.getValue(0));

                break;
                
            case STEP_4:
                
				s.Send(s.encrypt((Crypto_ByteArray) VAR_A_DAR3INVPA.getValue(1),aliases.get("ROLE_I")));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}