/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-12 13:42:28.346021 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/
package nspk_s_2;

import anbxj.AnBx_Layers;
import anbxj.AnB_Crypto_Wrapper;

public class NSPK_S_2 {

	final static AnBx_Layers layer = AnBx_Layers.APPLICATION;

	public static void main(String[] args) {

		try {
            if (args == null || args.length == 0) {
                System.err.printf("NSPK_S_2 - No arguments provided");
                System.exit(1);
            }
            
            AnB_Crypto_Wrapper.setLoggingExecTimeEnabled(false);
            long start = System.nanoTime();

            NSPK_S_2_CommandLine_Parser p = new NSPK_S_2_CommandLine_Parser(args,NSPK_S_2.class.getSimpleName());

            long end = System.nanoTime();
            double durationInMs = (end - start) / 1_000_000.0;
            System.out.printf("NSPK_S_2 [%s] - Execution time was %.3f ms%n", p.getRole(), durationInMs);

        } catch (IllegalArgumentException e) {
            System.err.printf("NSPK_S_2 - Configuration error: %s%n", e.getMessage());
            System.exit(1);
        } catch (Exception e) {
            System.err.printf("NSPK_S_2 - Unexpected error", e);
            System.exit(1);
        }
	}
}