/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-12 14:50:48.354847 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isopk2pmap_a1;

public enum ISOPK2PMAP_A1_Channels {

    ROLE_I_channel_ROLE_s_Server_Insecure, ROLE_s_channel_ROLE_I_Client_Insecure, ROLE_A_channel_ROLE_I_Server_Insecure, ROLE_I_channel_ROLE_A_Client_Insecure, ROLE_B_channel_ROLE_I_Server_Insecure, ROLE_I_channel_ROLE_B_Client_Insecure

}