/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 10:37:28.529267 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package isosk2pmap_a1;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class ISOSK2PMAP_A1_ROLE_B extends AnB_Protocol<ISOSK2PMAP_A1_Steps,ISOSK2PMAP_A1_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	
	// local vars
	private SecretKey ShkAB = null;
	private Crypto_ByteArray NB = null;
	private Crypto_ByteArray Text3 = null;
	private SealedObject VAR_B_R1 = null;
	private SecretKey VAR_B_SHKAB = null;
	
	
	public ISOSK2PMAP_A1_ROLE_B(ISOSK2PMAP_A1_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
         ShkAB = (SecretKey) AnB_Session.readObject(sharepath+"shk_"+aliases.get("ROLE_A")+"_"+aliases.get("ROLE_B")+".ser");
		};

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		ISOSK2PMAP_A1_ROLE_B.sessions = sessions;
		
		AnB_Session ROLE_B_channel_ROLE_I_Server_Insecure = lbs.get("ROLE_B_channel_ROLE_I_Server_Insecure");
        
		init();
		
        try {
            ROLE_B_channel_ROLE_I_Server_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_B_channel_ROLE_I_Server_Insecure, ISOSK2PMAP_A1_Steps.STEP_1);
                executeStep(ROLE_B_channel_ROLE_I_Server_Insecure, ISOSK2PMAP_A1_Steps.STEP_2);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_B_channel_ROLE_I_Server_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, ISOSK2PMAP_A1_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_1:
                
				VAR_B_R1 = (SealedObject) s.Receive();
				VAR_B_SHKAB = ShkAB;
				eqCheck("1.1",aliases.get("ROLE_B"),(String) new AnBx_Params((AnBx_Params) s.decrypt(VAR_B_R1,VAR_B_SHKAB)).getValue(1));
				//SB: added to log the recovery of Text1
				wffCheck("1.2",(Crypto_ByteArray) new AnBx_Params((AnBx_Params) s.decrypt(VAR_B_R1,VAR_B_SHKAB)).getValue(2));

                break;
                
            case STEP_2:

                NB = s.getNonce();
				Text3 = s.getNonce();

				s.Send(s.encrypt(new AnBx_Params(NB,aliases.get("ROLE_A"),Text3),VAR_B_SHKAB));

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}