'''
Author: S. Bernardi, J. Ezpeleta
Date: 1-January-2026

This module processes the goals (.goals) and results produced by the DLTL MC (.res) 
and produces the synthetized results in a human readable format (.res_s)

Input files: 

- <protocol>.goals  <--- goals
- <protocol>.res    <--- results from the DLTL MC


Output file:

- <protocol>.res_s   <--- synthetized results in .csv format (delimiter=';')

#goal;outcome;list_of_sessions_that_violate_the_goal
auth:[Data],[C,SP];True;['02', '05', '07', '08', '10']

Usage:
> python3 res_synthesis.py <protocol>

'''

import sys
import re
import csv

DLTL_PATH = "../protocols/dltl_log/"

# ---------------------------------------------------------------------------
def retrieve_goals_results(prefixname):
#Pre: prefixname.goals file 
	filename = DLTL_PATH + prefixname
	#Retrieves the goals defined in the AnBx protocol (high level)
	goals = []
	with open(filename + '.goals', 'r') as fgoals:
		for line in fgoals:
			#parse GOAL
			goal_pattern = re.compile(r'^;GOAL\s(.+)')
			matched = goal_pattern.match(line)
			if matched:
				goal = matched.groups()[0]
				goal = goal.replace('?','')
				goals.append(goal)
	#Retrieves the results generated by the MC
	results = []
	with open(filename + '.res', 'r') as fres:
		for line in fres:
			tr_name, outcomes = line.split(',',maxsplit=1)
			tr_name = tr_name.split('_')[-1]
			outcomes = list(map(int,outcomes.strip().split(',')))
			results.append([tr_name, outcomes])
			print("Outcomes", outcomes)
	return goals, results

#---------------------------------------------------------------------------
def process_results(goals,results):

	res_synt = []
	n_tr = len(results) 
	n_g = len(goals)
	for g in range(n_g):
		tr_counter = 0
		counter_example = []
		#For each trace tr, check whether the "tr+g*n_tr" colunm is 0 or 1: if 1 add trace as c/example
		for tr in range(n_tr): 
			if results[tr][1][g] == 1:
				tr_counter += 1
				counter_example.append(results[tr][0])
		violated = (tr_counter != 0)
		res_synt.append([goals[g],violated, counter_example])

	return res_synt
#---------------------------------------------------------------------------
def save_results_to_csv(prefixname,res):

	filename = DLTL_PATH + prefixname
	with open(filename + '.res_s', 'w', newline='') as f:
		writer = csv.writer(f, delimiter=';')
		writer.writerows(res)

#---------------------------------------------------------------------------

def synthesize_results(filename):

	print("Retrieve goals and results of ", filename + "............................")
	goals,res = retrieve_goals_results(filename)
	res_s = process_results(goals,res)
	print(f'{res_s}')
	print("Saved synthesized results in ", filename + ".res_s ............................")
	save_results_to_csv(filename,res_s)

#---------------------------------------------------------------------------
if __name__ == "__main__":

	if len(sys.argv) == 2:
		synthesize_results(sys.argv[1]) #name of the protocol name (filename without extensions)
	else:
		print("Usage: python3 res_synthesis <protocol_name>")
		exit(1)

	

