/*

 AnBx Compiler and Code Generator

 Copyright 2011-2025 Paolo Modesti
 Copyright 2018-2025 SCM/SCDT/SCEDT, Teesside University
 Copyright 2016-2018 School of Computer Science, University of Sunderland
 Copyright 2013-2015 School of Computing Science, Newcastle University
 Copyright 2011-2012 DAIS, Universita' Ca' Foscari Venezia
 
 This file was automatically generated by the AnBx Compiler 2025.09 on 2026-03-13 13:06:52.080337 UTC -->

 AnBx is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.

 AnBx is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with AnBx. If not, see <http://www.gnu.org/licenses/>.

*/

package sso_a1;

import anbxj.AnBx_Debug;
import anbxj.AnBx_Layers;
import anbxj.AnBx_Params;
import anbxj.AnB_Protocol;
import anbxj.AnB_Crypto_Wrapper;
import anbxj.AnB_Session;
import anbxj.Crypto_KeyStoreType;
import anbxj.Crypto_ByteArray;
import anbxj.Crypto_HmacPair;
import anbxj.Crypto_SealedPair;
import anbxj.Crypto_KeyPair;

import java.security.KeyPair;
import java.security.PublicKey;
import java.security.SignedObject;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public final class SSO_A1_ROLE_I extends AnB_Protocol<SSO_A1_Steps,SSO_A1_Roles> {

//	private static boolean loop = false;
    private static final AtomicLong sessionID = new AtomicLong(0);

	// local knowledge - constants
	private static Crypto_ByteArray empty = new Crypto_ByteArray("empty".getBytes());
	
	// local vars
	private Crypto_ByteArray URI2 = null;
	private Crypto_ByteArray ID2 = null;
	private AnBx_Params VAR_I_R0 = null;
	private AnBx_Params VAR_I_R2 = null;
	private Crypto_ByteArray VAR_I_J33IR0 = null;
	private Crypto_SealedPair VAR_I_R4 = null;
	private Crypto_SealedPair VAR_I_R6 = null;
	private AnBx_Params VAR_I_R8 = null;
	private SignedObject VAR_I_J12IR8 = null;
	private Crypto_ByteArray VAR_I_R10 = null;
	
	
	public SSO_A1_ROLE_I(SSO_A1_Roles role, String name, String sharepath) {
		super();
		this.role = role;
		this.name = name;   
		this.sharepath = sharepath;
        sessionID.incrementAndGet();
	}

    protected void init() {
		// set abortOnFail
		setAbortOnFail(false);
        // init shared vars
        };

	public void run(Map<String, AnB_Session> lbs, Map<String, String> aliases, long sessions) {
        Objects.requireNonNull(lbs, "lsb cannot be null");
        Objects.requireNonNull(aliases, "aliases cannot be null");

		this.aliases = aliases;
		this.lbs = lbs;
		SSO_A1_ROLE_I.sessions = sessions;
		
		AnB_Session ROLE_I_channel_ROLE_C_Server_Secure = lbs.get("ROLE_I_channel_ROLE_C_Server_Secure");
        AnB_Session ROLE_I_channel_ROLE_SP_Client_Secure = lbs.get("ROLE_I_channel_ROLE_SP_Client_Secure");
        AnB_Session ROLE_I_channel_ROLE_C_Server_Insecure = lbs.get("ROLE_I_channel_ROLE_C_Server_Insecure");
        AnB_Session ROLE_I_channel_ROLE_idp_Client_Insecure = lbs.get("ROLE_I_channel_ROLE_idp_Client_Insecure");
        
		init();
		
        try {
            ROLE_I_channel_ROLE_C_Server_Secure.Open();
            ROLE_I_channel_ROLE_SP_Client_Secure.Open();
            ROLE_I_channel_ROLE_C_Server_Insecure.Open();
            ROLE_I_channel_ROLE_idp_Client_Insecure.Open();
              
            do {
                AnBx_Debug.out(layer, "Session started: " + sessionID.get() + "/" + sessions);

                executeStep(ROLE_I_channel_ROLE_C_Server_Secure, SSO_A1_Steps.STEP_0);
                executeStep(ROLE_I_channel_ROLE_SP_Client_Secure, SSO_A1_Steps.STEP_1);
                executeStep(ROLE_I_channel_ROLE_SP_Client_Secure, SSO_A1_Steps.STEP_2);
                executeStep(ROLE_I_channel_ROLE_C_Server_Secure, SSO_A1_Steps.STEP_3);
                executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, SSO_A1_Steps.STEP_4);
                executeStep(ROLE_I_channel_ROLE_idp_Client_Insecure, SSO_A1_Steps.STEP_5);
                executeStep(ROLE_I_channel_ROLE_idp_Client_Insecure, SSO_A1_Steps.STEP_6);
                executeStep(ROLE_I_channel_ROLE_C_Server_Insecure, SSO_A1_Steps.STEP_7);
                executeStep(ROLE_I_channel_ROLE_C_Server_Secure, SSO_A1_Steps.STEP_8);
                executeStep(ROLE_I_channel_ROLE_SP_Client_Secure, SSO_A1_Steps.STEP_9);
                executeStep(ROLE_I_channel_ROLE_SP_Client_Secure, SSO_A1_Steps.STEP_10);
                
                AnBx_Debug.out(layer, "Session completed: " + sessionID.get() + "/" + sessions);
                sessionID.incrementAndGet();

            } while ((sessionID.get() <= sessions && sessionID.get() < Long.MAX_VALUE) || sessions < 0);
        } finally {
            ROLE_I_channel_ROLE_C_Server_Secure.Close();
		    ROLE_I_channel_ROLE_SP_Client_Secure.Close();
		    ROLE_I_channel_ROLE_C_Server_Insecure.Close();
		    ROLE_I_channel_ROLE_idp_Client_Insecure.Close();
		    }
	};

	protected void executeStep(AnB_Session s, SSO_A1_Steps step) {
        try {
            status(step);

            switch (step) {
            
            case STEP_0:
                
				VAR_I_R0 = (AnBx_Params) s.Receive();
				eqCheck("0.1",aliases.get("ROLE_C"),(String) VAR_I_R0.getValue(0));

                break;
                
            case STEP_1:
                
				URI2 = s.getNonce();
				s.Send(new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_SP"),URI2));

                break;
                
            case STEP_2:
                
				VAR_I_R2 = (AnBx_Params) s.Receive();
				eqCheck("2.1",aliases.get("ROLE_C"),(String) VAR_I_R2.getValue(0));
				eqCheck("2.2",aliases.get("ROLE_SP"),(String) VAR_I_R2.getValue(2));
				eqCheck("2.3",aliases.get("ROLE_idp"),(String) VAR_I_R2.getValue(1));
				eqCheck("2.4",URI2,(Crypto_ByteArray) VAR_I_R2.getValue(4));

                break;
                
            case STEP_3:
                
				ID2 = s.getNonce();
				VAR_I_J33IR0 = (Crypto_ByteArray) VAR_I_R0.getValue(2);
				s.Send(new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_idp"),(String) VAR_I_R0.getValue(1),ID2,VAR_I_J33IR0));

                break;
                
            case STEP_4:
                
				VAR_I_R4 = (Crypto_SealedPair) s.Receive();
				wffCheck("4.1",VAR_I_R4);
				wffCheck("4.2",(Crypto_ByteArray) VAR_I_R2.getValue(3));

                break;
                
            case STEP_5:
                
				s.Send(VAR_I_R4);

                break;
                
            case STEP_6:
                
				VAR_I_R6 = (Crypto_SealedPair) s.Receive();
				wffCheck("6.1",VAR_I_R6);

                break;
                
            case STEP_7:
                
				s.Send(VAR_I_R6);

                break;
                
            case STEP_8:
                
				VAR_I_R8 = (AnBx_Params) s.Receive();
				eqCheck("8.1",VAR_I_J33IR0,(Crypto_ByteArray) VAR_I_R8.getValue(1));
				VAR_I_J12IR8 = (SignedObject) VAR_I_R8.getValue(0);
				eqCheck("8.2",(AnBx_Params) s.verify(VAR_I_J12IR8,aliases.get("ROLE_idp")),new AnBx_Params(aliases.get("ROLE_C"),aliases.get("ROLE_idp")));

                break;
                
            case STEP_9:
                
				s.Send(new AnBx_Params(VAR_I_J12IR8,URI2));

                break;
                
            case STEP_10:
                
				VAR_I_R10 = (Crypto_ByteArray) s.Receive();
				wffCheck("10.1",VAR_I_R10);

                break;
                
            default:
                
                break;		
            }

            status(step);
        } catch (ClassCastException e) {
            abort("Message format type error in Step " + step.name(),e,sessionID.get());
        } catch (NullPointerException e) {
            abort("Some data have not been properly initialised in Step " + step.name(),e,sessionID.get());
        } catch (Exception e) {
            abort("Generic error in Step " + step.name(),e,sessionID.get());
        }
	}

	

	
	

}